midas:
  kafka:
    topic:
      transactions: transactions

general:
  kafka-topic: ${midas.kafka.topic.transactions}

spring:
  kafka:
    # We will use the embedded kafka port if provided and fall back to predefined port otherwise
    bootstrap-servers: ${spring.embedded.kafka.brokers:localhost:57085}

    listener:
      missing-topics-fatal: false

    consumer:
      group-id: midas-core
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.jpmc.midascore.*"
        spring.json.value.default.type: "com.jpmc.midascore.foundation.Transaction"

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

datasource:
  url: jdbc:h2:mem:midas;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
  driver-class-name: org.h2.Driver
  username: sa
  password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  h2:
    console:
      enabled: true

logging:
  level:
    com.jpmc.midascore.kafka: DEBUG